{{cpp/title|perror}}
{{cpp/io/c/navbar}}
{{ddcl|header=cstdio|
void perror( const char *s );
}}

Prints a textual description of the error code currently stored in the system variable {{lc|errno}} to {{lc|stderr}}.

The description is formed by concatenating the following components:
* the contents of the null-terminated byte string pointed to by {{c|s}}, followed by {{c|": "}} (unless {{c|s}} is a null pointer or the character pointed to by {{c|s}} is the null character).
* implementation-defined error message string describing the error code stored in {{tt|errno}}, followed by {{c|'\n'}}. The error message string is identical to the result of {{c|std::strerror(errno)}}.

===Parameters===
{{par begin}}
{{par|s|pointer to a null-terminated string with explanatory message}}
{{par end}}

===Return value===
(none)

===Example===
{{example
|code=
#include &lt;cerrno&gt;
#include &lt;cmath&gt;
#include &lt;cstdio&gt;

int main()
{
    double not_a_number = std::log(-1.0);
    if (errno == EDOM)
        std::perror("log(-1) failed");
    std::printf("%f\n", not_a_number);
}
|p=true
|output=
log(-1) failed: Numerical argument out of domain
nan
}}

===See also===
{{dsc begin}}
{{dsc inc|cpp/error/dsc errno}}
{{dsc inc|cpp/string/byte/dsc strerror}}
{{dsc see c|c/io/perror}}
{{dsc end}}

{{langlinks|de|es|fr|it|ja|pt|ru|zh}}